[package]
name = "demex"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { features = ["default"], version = "0.27.2" }
egui_extras = { features = ["default"], version = "0.27.2" }
open_dmx = "1.1.1"
rand = "0.8.5"
ref-map = "0.1.3"
