/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 89
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_integer = 1,
  sym_float = 2,
  sym_string = 3,
  anon_sym_group = 4,
  anon_sym_g = 5,
  anon_sym_sequence = 6,
  anon_sym_seq = 7,
  anon_sym_executor = 8,
  anon_sym_exec = 9,
  anon_sym_set = 10,
  anon_sym_home = 11,
  anon_sym_clear = 12,
  anon_sym_record = 13,
  anon_sym_save = 14,
  anon_sym_lock = 15,
  anon_sym_test = 16,
  anon_sym_nuzul = 17,
  anon_sym_sueud = 18,
  anon_sym_grandetc = 19,
  anon_sym_as = 20,
  anon_sym_preset = 21,
  anon_sym_next = 22,
  anon_sym_for = 23,
  anon_sym_cue = 24,
  anon_sym_PLUS = 25,
  anon_sym_DASH = 26,
  anon_sym_PERCENT = 27,
  anon_sym_thru = 28,
  anon_sym_LPAREN = 29,
  anon_sym_RPAREN = 30,
  anon_sym_TILDE = 31,
  anon_sym_DOT = 32,
  anon_sym_intens = 33,
  anon_sym_AT = 34,
  anon_sym_full = 35,
  anon_sym_half = 36,
  anon_sym_out = 37,
  sym_command = 38,
  sym_group = 39,
  sym_sequence = 40,
  sym_executor = 41,
  sym_function_call = 42,
  sym_set_function_call = 43,
  sym_set_property_function = 44,
  sym_as = 45,
  sym_record_function = 46,
  sym_object = 47,
  sym_homeable_object = 48,
  sym_fixture_selector = 49,
  sym_atomic_fixture_selector = 50,
  sym_preset_id = 51,
  sym_specific_preset = 52,
  sym_specific_preset_or_range = 53,
  sym_specific_sequence = 54,
  sym_specific_sequence_cue = 55,
  sym_specific_executor = 56,
  sym_specific_group = 57,
  sym_channel_attribute = 58,
  sym_channel_value = 59,
  sym_discrete_channel_value = 60,
  aux_sym_fixture_selector_repeat1 = 61,
  aux_sym_fixture_selector_repeat2 = 62,
  aux_sym_fixture_selector_repeat3 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_integer] = "integer",
  [sym_float] = "float",
  [sym_string] = "string",
  [anon_sym_group] = "group",
  [anon_sym_g] = "g",
  [anon_sym_sequence] = "sequence",
  [anon_sym_seq] = "seq",
  [anon_sym_executor] = "executor",
  [anon_sym_exec] = "exec",
  [anon_sym_set] = "set",
  [anon_sym_home] = "home",
  [anon_sym_clear] = "clear",
  [anon_sym_record] = "record",
  [anon_sym_save] = "save",
  [anon_sym_lock] = "lock",
  [anon_sym_test] = "test",
  [anon_sym_nuzul] = "nuzul",
  [anon_sym_sueud] = "sueud",
  [anon_sym_grandetc] = "grandetc",
  [anon_sym_as] = "as",
  [anon_sym_preset] = "preset",
  [anon_sym_next] = "next",
  [anon_sym_for] = "for",
  [anon_sym_cue] = "cue",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_PERCENT] = "%",
  [anon_sym_thru] = "thru",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TILDE] = "~",
  [anon_sym_DOT] = ".",
  [anon_sym_intens] = "intens",
  [anon_sym_AT] = "@",
  [anon_sym_full] = "full",
  [anon_sym_half] = "half",
  [anon_sym_out] = "out",
  [sym_command] = "command",
  [sym_group] = "group",
  [sym_sequence] = "sequence",
  [sym_executor] = "executor",
  [sym_function_call] = "function_call",
  [sym_set_function_call] = "set_function_call",
  [sym_set_property_function] = "set_property_function",
  [sym_as] = "as",
  [sym_record_function] = "record_function",
  [sym_object] = "object",
  [sym_homeable_object] = "homeable_object",
  [sym_fixture_selector] = "fixture_selector",
  [sym_atomic_fixture_selector] = "atomic_fixture_selector",
  [sym_preset_id] = "preset_id",
  [sym_specific_preset] = "specific_preset",
  [sym_specific_preset_or_range] = "specific_preset_or_range",
  [sym_specific_sequence] = "specific_sequence",
  [sym_specific_sequence_cue] = "specific_sequence_cue",
  [sym_specific_executor] = "specific_executor",
  [sym_specific_group] = "specific_group",
  [sym_channel_attribute] = "channel_attribute",
  [sym_channel_value] = "channel_value",
  [sym_discrete_channel_value] = "discrete_channel_value",
  [aux_sym_fixture_selector_repeat1] = "fixture_selector_repeat1",
  [aux_sym_fixture_selector_repeat2] = "fixture_selector_repeat2",
  [aux_sym_fixture_selector_repeat3] = "fixture_selector_repeat3",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_integer] = sym_integer,
  [sym_float] = sym_float,
  [sym_string] = sym_string,
  [anon_sym_group] = anon_sym_group,
  [anon_sym_g] = anon_sym_g,
  [anon_sym_sequence] = anon_sym_sequence,
  [anon_sym_seq] = anon_sym_seq,
  [anon_sym_executor] = anon_sym_executor,
  [anon_sym_exec] = anon_sym_exec,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_home] = anon_sym_home,
  [anon_sym_clear] = anon_sym_clear,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_save] = anon_sym_save,
  [anon_sym_lock] = anon_sym_lock,
  [anon_sym_test] = anon_sym_test,
  [anon_sym_nuzul] = anon_sym_nuzul,
  [anon_sym_sueud] = anon_sym_sueud,
  [anon_sym_grandetc] = anon_sym_grandetc,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_preset] = anon_sym_preset,
  [anon_sym_next] = anon_sym_next,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_cue] = anon_sym_cue,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_thru] = anon_sym_thru,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_intens] = anon_sym_intens,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_full] = anon_sym_full,
  [anon_sym_half] = anon_sym_half,
  [anon_sym_out] = anon_sym_out,
  [sym_command] = sym_command,
  [sym_group] = sym_group,
  [sym_sequence] = sym_sequence,
  [sym_executor] = sym_executor,
  [sym_function_call] = sym_function_call,
  [sym_set_function_call] = sym_set_function_call,
  [sym_set_property_function] = sym_set_property_function,
  [sym_as] = sym_as,
  [sym_record_function] = sym_record_function,
  [sym_object] = sym_object,
  [sym_homeable_object] = sym_homeable_object,
  [sym_fixture_selector] = sym_fixture_selector,
  [sym_atomic_fixture_selector] = sym_atomic_fixture_selector,
  [sym_preset_id] = sym_preset_id,
  [sym_specific_preset] = sym_specific_preset,
  [sym_specific_preset_or_range] = sym_specific_preset_or_range,
  [sym_specific_sequence] = sym_specific_sequence,
  [sym_specific_sequence_cue] = sym_specific_sequence_cue,
  [sym_specific_executor] = sym_specific_executor,
  [sym_specific_group] = sym_specific_group,
  [sym_channel_attribute] = sym_channel_attribute,
  [sym_channel_value] = sym_channel_value,
  [sym_discrete_channel_value] = sym_discrete_channel_value,
  [aux_sym_fixture_selector_repeat1] = aux_sym_fixture_selector_repeat1,
  [aux_sym_fixture_selector_repeat2] = aux_sym_fixture_selector_repeat2,
  [aux_sym_fixture_selector_repeat3] = aux_sym_fixture_selector_repeat3,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_group] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_g] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sequence] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_executor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_exec] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_home] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clear] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_save] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lock] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_test] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nuzul] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sueud] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_grandetc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_preset] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_next] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_thru] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_intens] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_full] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_half] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_group] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_executor] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_set_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_set_property_function] = {
    .visible = true,
    .named = true,
  },
  [sym_as] = {
    .visible = true,
    .named = true,
  },
  [sym_record_function] = {
    .visible = true,
    .named = true,
  },
  [sym_object] = {
    .visible = true,
    .named = true,
  },
  [sym_homeable_object] = {
    .visible = true,
    .named = true,
  },
  [sym_fixture_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_atomic_fixture_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_preset_id] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_preset] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_preset_or_range] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_sequence_cue] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_executor] = {
    .visible = true,
    .named = true,
  },
  [sym_specific_group] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_channel_value] = {
    .visible = true,
    .named = true,
  },
  [sym_discrete_channel_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_fixture_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fixture_selector_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_fixture_selector_repeat3] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_object,
    [1] = sym_object,
  },
  [2] = {
    [0] = sym_object,
    [1] = sym_object,
    [2] = sym_object,
    [3] = sym_object,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_group, 2,
    sym_group,
    sym_object,
  sym_sequence, 2,
    sym_sequence,
    sym_object,
  sym_executor, 2,
    sym_executor,
    sym_object,
  sym_preset_id, 2,
    sym_preset_id,
    sym_object,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(78);
      ADVANCE_MAP(
        '"', 1,
        '%', 106,
        '(', 108,
        ')', 109,
        '+', 104,
        '-', 105,
        '.', 111,
        '@', 113,
        'a', 56,
        'c', 37,
        'e', 75,
        'f', 45,
        'g', 84,
        'h', 6,
        'i', 40,
        'l', 44,
        'n', 23,
        'o', 70,
        'p', 54,
        'r', 24,
        's', 3,
        't', 21,
        '~', 110,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '.') ADVANCE(77);
      if (lookahead == 'f') ADVANCE(67);
      if (lookahead == 'h') ADVANCE(5);
      if (lookahead == 'n') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(70);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(73);
      if (lookahead == 'e') ADVANCE(49);
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(41);
      if (lookahead == 'o') ADVANCE(68);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(34);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(34);
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(88);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(98);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(92);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(103);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(58);
      if (lookahead == 'h') ADVANCE(55);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(74);
      if (lookahead == 'u') ADVANCE(76);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(64);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(115);
      END_STATE();
    case 33:
      if (lookahead == 'k') ADVANCE(94);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(114);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(96);
      END_STATE();
    case 37:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(57);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 44:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(50);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(83);
      END_STATE();
    case 49:
      if (lookahead == 'q') ADVANCE(86);
      if (lookahead == 't') ADVANCE(89);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(102);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(91);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(69);
      END_STATE();
    case 56:
      if (lookahead == 's') ADVANCE(99);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(112);
      END_STATE();
    case 58:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 59:
      if (lookahead == 's') ADVANCE(30);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(116);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(95);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(100);
      END_STATE();
    case 64:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 67:
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 68:
      if (lookahead == 'u') ADVANCE(48);
      END_STATE();
    case 69:
      if (lookahead == 'u') ADVANCE(107);
      END_STATE();
    case 70:
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 71:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 72:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 73:
      if (lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 74:
      if (lookahead == 'x') ADVANCE(61);
      END_STATE();
    case 75:
      if (lookahead == 'x') ADVANCE(27);
      END_STATE();
    case 76:
      if (lookahead == 'z') ADVANCE(72);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_float);
      if (lookahead == '.') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_float);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_group);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_g);
      if (lookahead == 'r') ADVANCE(4);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_sequence);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_seq);
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_executor);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_exec);
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_home);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_clear);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_save);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_lock);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_test);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_nuzul);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_sueud);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_grandetc);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_preset);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_next);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_cue);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_thru);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_intens);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_full);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(anon_sym_half);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_group] = ACTIONS(1),
    [anon_sym_g] = ACTIONS(1),
    [anon_sym_sequence] = ACTIONS(1),
    [anon_sym_seq] = ACTIONS(1),
    [anon_sym_executor] = ACTIONS(1),
    [anon_sym_exec] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_home] = ACTIONS(1),
    [anon_sym_clear] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_save] = ACTIONS(1),
    [anon_sym_lock] = ACTIONS(1),
    [anon_sym_test] = ACTIONS(1),
    [anon_sym_nuzul] = ACTIONS(1),
    [anon_sym_sueud] = ACTIONS(1),
    [anon_sym_grandetc] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_preset] = ACTIONS(1),
    [anon_sym_next] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_cue] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_thru] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_intens] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_full] = ACTIONS(1),
    [anon_sym_half] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_command] = STATE(66),
    [sym_group] = STATE(82),
    [sym_sequence] = STATE(58),
    [sym_executor] = STATE(59),
    [sym_function_call] = STATE(64),
    [sym_object] = STATE(64),
    [sym_homeable_object] = STATE(45),
    [sym_fixture_selector] = STATE(27),
    [sym_atomic_fixture_selector] = STATE(4),
    [sym_specific_preset] = STATE(45),
    [sym_specific_sequence] = STATE(34),
    [sym_specific_sequence_cue] = STATE(45),
    [sym_specific_executor] = STATE(47),
    [sym_specific_group] = STATE(6),
    [sym_integer] = ACTIONS(3),
    [anon_sym_group] = ACTIONS(5),
    [anon_sym_g] = ACTIONS(7),
    [anon_sym_sequence] = ACTIONS(9),
    [anon_sym_seq] = ACTIONS(11),
    [anon_sym_executor] = ACTIONS(13),
    [anon_sym_exec] = ACTIONS(15),
    [anon_sym_set] = ACTIONS(17),
    [anon_sym_home] = ACTIONS(19),
    [anon_sym_clear] = ACTIONS(21),
    [anon_sym_record] = ACTIONS(23),
    [anon_sym_save] = ACTIONS(21),
    [anon_sym_lock] = ACTIONS(21),
    [anon_sym_test] = ACTIONS(25),
    [anon_sym_nuzul] = ACTIONS(21),
    [anon_sym_sueud] = ACTIONS(21),
    [anon_sym_grandetc] = ACTIONS(21),
    [anon_sym_preset] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_TILDE] = ACTIONS(31),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(9), 1,
      anon_sym_sequence,
    ACTIONS(11), 1,
      anon_sym_seq,
    ACTIONS(13), 1,
      anon_sym_executor,
    ACTIONS(15), 1,
      anon_sym_exec,
    ACTIONS(27), 1,
      anon_sym_preset,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(34), 1,
      sym_specific_sequence,
    STATE(58), 1,
      sym_sequence,
    STATE(59), 1,
      sym_executor,
    STATE(62), 1,
      sym_set_property_function,
    STATE(63), 1,
      sym_object,
    STATE(82), 1,
      sym_group,
    STATE(47), 2,
      sym_fixture_selector,
      sym_specific_executor,
    STATE(45), 3,
      sym_homeable_object,
      sym_specific_preset,
      sym_specific_sequence_cue,
  [64] = 14,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(13), 1,
      anon_sym_executor,
    ACTIONS(15), 1,
      anon_sym_exec,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(59), 1,
      sym_executor,
    STATE(62), 1,
      sym_homeable_object,
    STATE(82), 1,
      sym_group,
    STATE(47), 2,
      sym_fixture_selector,
      sym_specific_executor,
  [108] = 7,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    ACTIONS(39), 1,
      anon_sym_DASH,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    STATE(10), 1,
      aux_sym_fixture_selector_repeat1,
    STATE(11), 1,
      aux_sym_fixture_selector_repeat3,
    STATE(12), 1,
      aux_sym_fixture_selector_repeat2,
    ACTIONS(35), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [137] = 2,
    ACTIONS(45), 1,
      anon_sym_thru,
    ACTIONS(43), 11,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [154] = 1,
    ACTIONS(43), 11,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [168] = 1,
    ACTIONS(47), 11,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [182] = 11,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(9), 1,
      anon_sym_sequence,
    ACTIONS(11), 1,
      anon_sym_seq,
    ACTIONS(13), 1,
      anon_sym_executor,
    ACTIONS(15), 1,
      anon_sym_exec,
    ACTIONS(49), 1,
      anon_sym_preset,
    STATE(49), 1,
      sym_group,
    STATE(62), 1,
      sym_record_function,
    STATE(68), 1,
      sym_sequence,
    STATE(69), 1,
      sym_executor,
  [216] = 1,
    ACTIONS(51), 11,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [230] = 3,
    ACTIONS(37), 1,
      anon_sym_PLUS,
    STATE(15), 1,
      aux_sym_fixture_selector_repeat1,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [247] = 3,
    ACTIONS(41), 1,
      anon_sym_PERCENT,
    STATE(14), 1,
      aux_sym_fixture_selector_repeat3,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [264] = 3,
    ACTIONS(39), 1,
      anon_sym_DASH,
    STATE(13), 1,
      aux_sym_fixture_selector_repeat2,
    ACTIONS(53), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [281] = 3,
    ACTIONS(57), 1,
      anon_sym_DASH,
    STATE(13), 1,
      aux_sym_fixture_selector_repeat2,
    ACTIONS(55), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [298] = 3,
    ACTIONS(62), 1,
      anon_sym_PERCENT,
    STATE(14), 1,
      aux_sym_fixture_selector_repeat3,
    ACTIONS(60), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [315] = 3,
    ACTIONS(67), 1,
      anon_sym_PLUS,
    STATE(15), 1,
      aux_sym_fixture_selector_repeat1,
    ACTIONS(65), 8,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [332] = 9,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(38), 1,
      sym_fixture_selector,
    STATE(82), 1,
      sym_group,
  [360] = 1,
    ACTIONS(65), 9,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PLUS,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [372] = 1,
    ACTIONS(55), 9,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_DASH,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [384] = 1,
    ACTIONS(60), 9,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_as,
      anon_sym_preset,
      anon_sym_next,
      anon_sym_PERCENT,
      anon_sym_RPAREN,
      anon_sym_intens,
      anon_sym_AT,
  [396] = 9,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(32), 1,
      sym_fixture_selector,
    STATE(82), 1,
      sym_group,
  [424] = 9,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(37), 1,
      sym_fixture_selector,
    STATE(82), 1,
      sym_group,
  [452] = 9,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(82), 1,
      sym_group,
    STATE(86), 1,
      sym_fixture_selector,
  [480] = 9,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(4), 1,
      sym_atomic_fixture_selector,
    STATE(6), 1,
      sym_specific_group,
    STATE(82), 1,
      sym_group,
    STATE(85), 1,
      sym_fixture_selector,
  [508] = 8,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(6), 1,
      sym_specific_group,
    STATE(17), 1,
      sym_atomic_fixture_selector,
    STATE(82), 1,
      sym_group,
  [533] = 8,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(6), 1,
      sym_specific_group,
    STATE(19), 1,
      sym_atomic_fixture_selector,
    STATE(82), 1,
      sym_group,
  [558] = 8,
    ACTIONS(3), 1,
      sym_integer,
    ACTIONS(5), 1,
      anon_sym_group,
    ACTIONS(7), 1,
      anon_sym_g,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      anon_sym_TILDE,
    STATE(6), 1,
      sym_specific_group,
    STATE(18), 1,
      sym_atomic_fixture_selector,
    STATE(82), 1,
      sym_group,
  [583] = 7,
    ACTIONS(27), 1,
      anon_sym_preset,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_channel_attribute,
    STATE(44), 1,
      sym_specific_preset,
    STATE(61), 1,
      sym_specific_preset_or_range,
    STATE(62), 1,
      sym_set_function_call,
    ACTIONS(72), 2,
      anon_sym_intens,
      anon_sym_AT,
  [606] = 3,
    STATE(40), 1,
      sym_discrete_channel_value,
    STATE(56), 1,
      sym_channel_value,
    ACTIONS(74), 4,
      sym_float,
      anon_sym_full,
      anon_sym_half,
      anon_sym_out,
  [619] = 2,
    STATE(77), 1,
      sym_discrete_channel_value,
    ACTIONS(74), 4,
      sym_float,
      anon_sym_full,
      anon_sym_half,
      anon_sym_out,
  [629] = 1,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_for,
      anon_sym_thru,
  [636] = 1,
    ACTIONS(78), 4,
      sym_float,
      anon_sym_full,
      anon_sym_half,
      anon_sym_out,
  [643] = 4,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      anon_sym_as,
    ACTIONS(84), 1,
      anon_sym_next,
    STATE(51), 1,
      sym_as,
  [656] = 1,
    ACTIONS(86), 3,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_cue,
  [662] = 2,
    ACTIONS(90), 1,
      anon_sym_cue,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_string,
  [670] = 1,
    ACTIONS(92), 3,
      ts_builtin_sym_end,
      sym_string,
      anon_sym_thru,
  [676] = 3,
    ACTIONS(94), 1,
      sym_integer,
    ACTIONS(96), 1,
      anon_sym_next,
    STATE(74), 1,
      sym_preset_id,
  [686] = 3,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      anon_sym_as,
    STATE(79), 1,
      sym_as,
  [696] = 3,
    ACTIONS(82), 1,
      anon_sym_as,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    STATE(87), 1,
      sym_as,
  [706] = 1,
    ACTIONS(100), 2,
      sym_integer,
      anon_sym_next,
  [711] = 2,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 1,
      anon_sym_thru,
  [718] = 2,
    ACTIONS(27), 1,
      anon_sym_preset,
    STATE(88), 1,
      sym_specific_preset,
  [725] = 1,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_thru,
  [730] = 1,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      sym_string,
  [735] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 1,
      anon_sym_thru,
  [742] = 1,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      sym_string,
  [747] = 1,
    ACTIONS(114), 2,
      ts_builtin_sym_end,
      sym_string,
  [752] = 1,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      sym_string,
  [757] = 1,
    ACTIONS(116), 2,
      sym_float,
      anon_sym_next,
  [762] = 1,
    ACTIONS(118), 2,
      sym_integer,
      anon_sym_next,
  [767] = 1,
    ACTIONS(120), 2,
      sym_float,
      anon_sym_next,
  [772] = 2,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
    ACTIONS(124), 1,
      anon_sym_next,
  [779] = 2,
    ACTIONS(94), 1,
      sym_integer,
    STATE(35), 1,
      sym_preset_id,
  [786] = 2,
    ACTIONS(126), 1,
      anon_sym_for,
    ACTIONS(128), 1,
      anon_sym_cue,
  [793] = 1,
    ACTIONS(130), 2,
      ts_builtin_sym_end,
      anon_sym_next,
  [798] = 1,
    ACTIONS(126), 1,
      anon_sym_for,
  [802] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [806] = 1,
    ACTIONS(134), 1,
      sym_integer,
  [810] = 1,
    ACTIONS(136), 1,
      sym_integer,
  [814] = 1,
    ACTIONS(138), 1,
      sym_integer,
  [818] = 1,
    ACTIONS(140), 1,
      sym_integer,
  [822] = 1,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
  [826] = 1,
    ACTIONS(144), 1,
      ts_builtin_sym_end,
  [830] = 1,
    ACTIONS(146), 1,
      sym_string,
  [834] = 1,
    ACTIONS(148), 1,
      ts_builtin_sym_end,
  [838] = 1,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
  [842] = 1,
    ACTIONS(152), 1,
      ts_builtin_sym_end,
  [846] = 1,
    ACTIONS(154), 1,
      sym_integer,
  [850] = 1,
    ACTIONS(156), 1,
      sym_integer,
  [854] = 1,
    ACTIONS(158), 1,
      sym_integer,
  [858] = 1,
    ACTIONS(160), 1,
      sym_integer,
  [862] = 1,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
  [866] = 1,
    ACTIONS(162), 1,
      sym_string,
  [870] = 1,
    ACTIONS(164), 1,
      sym_string,
  [874] = 1,
    ACTIONS(166), 1,
      anon_sym_for,
  [878] = 1,
    ACTIONS(168), 1,
      anon_sym_for,
  [882] = 1,
    ACTIONS(170), 1,
      anon_sym_for,
  [886] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
  [890] = 1,
    ACTIONS(174), 1,
      sym_string,
  [894] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [898] = 1,
    ACTIONS(176), 1,
      anon_sym_DOT,
  [902] = 1,
    ACTIONS(178), 1,
      anon_sym_cue,
  [906] = 1,
    ACTIONS(180), 1,
      sym_integer,
  [910] = 1,
    ACTIONS(182), 1,
      sym_integer,
  [914] = 1,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
  [918] = 1,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [922] = 1,
    ACTIONS(140), 1,
      anon_sym_RPAREN,
  [926] = 1,
    ACTIONS(186), 1,
      ts_builtin_sym_end,
  [930] = 1,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 64,
  [SMALL_STATE(4)] = 108,
  [SMALL_STATE(5)] = 137,
  [SMALL_STATE(6)] = 154,
  [SMALL_STATE(7)] = 168,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 216,
  [SMALL_STATE(10)] = 230,
  [SMALL_STATE(11)] = 247,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 281,
  [SMALL_STATE(14)] = 298,
  [SMALL_STATE(15)] = 315,
  [SMALL_STATE(16)] = 332,
  [SMALL_STATE(17)] = 360,
  [SMALL_STATE(18)] = 372,
  [SMALL_STATE(19)] = 384,
  [SMALL_STATE(20)] = 396,
  [SMALL_STATE(21)] = 424,
  [SMALL_STATE(22)] = 452,
  [SMALL_STATE(23)] = 480,
  [SMALL_STATE(24)] = 508,
  [SMALL_STATE(25)] = 533,
  [SMALL_STATE(26)] = 558,
  [SMALL_STATE(27)] = 583,
  [SMALL_STATE(28)] = 606,
  [SMALL_STATE(29)] = 619,
  [SMALL_STATE(30)] = 629,
  [SMALL_STATE(31)] = 636,
  [SMALL_STATE(32)] = 643,
  [SMALL_STATE(33)] = 656,
  [SMALL_STATE(34)] = 662,
  [SMALL_STATE(35)] = 670,
  [SMALL_STATE(36)] = 676,
  [SMALL_STATE(37)] = 686,
  [SMALL_STATE(38)] = 696,
  [SMALL_STATE(39)] = 706,
  [SMALL_STATE(40)] = 711,
  [SMALL_STATE(41)] = 718,
  [SMALL_STATE(42)] = 725,
  [SMALL_STATE(43)] = 730,
  [SMALL_STATE(44)] = 735,
  [SMALL_STATE(45)] = 742,
  [SMALL_STATE(46)] = 747,
  [SMALL_STATE(47)] = 752,
  [SMALL_STATE(48)] = 757,
  [SMALL_STATE(49)] = 762,
  [SMALL_STATE(50)] = 767,
  [SMALL_STATE(51)] = 772,
  [SMALL_STATE(52)] = 779,
  [SMALL_STATE(53)] = 786,
  [SMALL_STATE(54)] = 793,
  [SMALL_STATE(55)] = 798,
  [SMALL_STATE(56)] = 802,
  [SMALL_STATE(57)] = 806,
  [SMALL_STATE(58)] = 810,
  [SMALL_STATE(59)] = 814,
  [SMALL_STATE(60)] = 818,
  [SMALL_STATE(61)] = 822,
  [SMALL_STATE(62)] = 826,
  [SMALL_STATE(63)] = 830,
  [SMALL_STATE(64)] = 834,
  [SMALL_STATE(65)] = 838,
  [SMALL_STATE(66)] = 842,
  [SMALL_STATE(67)] = 846,
  [SMALL_STATE(68)] = 850,
  [SMALL_STATE(69)] = 854,
  [SMALL_STATE(70)] = 858,
  [SMALL_STATE(71)] = 862,
  [SMALL_STATE(72)] = 866,
  [SMALL_STATE(73)] = 870,
  [SMALL_STATE(74)] = 874,
  [SMALL_STATE(75)] = 878,
  [SMALL_STATE(76)] = 882,
  [SMALL_STATE(77)] = 886,
  [SMALL_STATE(78)] = 890,
  [SMALL_STATE(79)] = 894,
  [SMALL_STATE(80)] = 898,
  [SMALL_STATE(81)] = 902,
  [SMALL_STATE(82)] = 906,
  [SMALL_STATE(83)] = 910,
  [SMALL_STATE(84)] = 914,
  [SMALL_STATE(85)] = 918,
  [SMALL_STATE(86)] = 922,
  [SMALL_STATE(87)] = 926,
  [SMALL_STATE(88)] = 930,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fixture_selector, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic_fixture_selector, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_group, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic_fixture_selector, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fixture_selector, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat2, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat2, 2, 0, 0), SHIFT_REPEAT(26),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat3, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat3, 2, 0, 0), SHIFT_REPEAT(25),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_fixture_selector_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_homeable_object, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preset_id, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_attribute, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_function, 4, 0, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_sequence, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_preset, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_function, 6, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_group, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_value, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_discrete_channel_value, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_executor, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_preset_or_range, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_sequence_cue, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_function, 5, 0, 1),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_as, 2, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_function_call, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_function_call, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_property_function, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_executor, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_channel_value, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_function, 6, 0, 2),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_function, 7, 0, 1),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_specific_preset_or_range, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_demex(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "demex",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
