[package]
name="demex_ui"
version.workspace = true
edition.workspace = true

[dependencies]
gpui = { git = "https://github.com/zed-industries/zed", optional = true }
eyre = "0.6.12"
rust-embed = "8.7.2"
smallvec = "1.15.1"
log.workspace = true
regex.workspace = true

[features]
default = ["gpui"]
gpui = ["dep:gpui"]
