[package]
name = "demex_gpui"
version.workspace = true
edition.workspace = true

[dependencies]
rfd = { version = "0.17.1"}
open = { version = "5.3.2"}

# gpui = { version = "*", features = ["leak-detection"] }
gpui = { git = "https://github.com/zed-industries/zed"  }

# gpui-component = { path = "../../../gpui-component/crates/ui" }
gpui-component = { git = "https://github.com/matteolutz/gpui-component", branch = "main" }

anyhow = {version = "1.0.100" }

ecolor.workspace = true
emath.workspace = true

chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
gdtf.workspace = true
interpolator.workspace = true
itertools.workspace = true
log.workspace = true
parking_lot.workspace = true
regex.workspace = true

serde.workspace = true
serde_json.workspace = true

strum.workspace = true
strum_macros.workspace = true

serialport.workspace = true

demex_headless.workspace = true
demex_dmx.workspace = true
demex_core.workspace = true
tree-sitter-demex.workspace = true
rust-embed = "8.9.0"
dirs = "6.0.0"
smol = "2.0.2"
