[package]
name="demex_core"
version.workspace = true
edition.workspace = true

[dependencies]
demex_headless.workspace = true
demex_dmx.workspace = true

serde.workspace = true
serde_json.workspace = true
byteorder.workspace = true
strum.workspace = true
strum_macros.workspace = true
lazy_static.workspace = true
regex.workspace = true
gdtf.workspace = true
ciborium.workspace = true
emath.workspace = true
ecolor.workspace = true
itertools.workspace = true
uuid.workspace = true
parking_lot.workspace = true
nalgebra.workspace = true
log.workspace = true
midir.workspace = true

[dev-dependencies]
approx = "0.5.1"
