[package]
name = "tree-sitter-demex"
version.workspace = true
edition.workspace = true

description = "Demex grammar for tree-sitter"
authors = ["Matteo Lutz <info@matteolutz.de>"]
license = "MIT"
readme = "README.md"
keywords = ["incremental", "parsing", "tree-sitter", "demex"]
categories = ["parser-implementations", "parsing", "text-editors"]
repository = "https://github.com/matteolutz/demex"
autoexamples = false

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
  "tree-sitter.json",
  "/LICENSE",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.2"

[dev-dependencies]
tree-sitter = "0.25.10"
