use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Token {
    Integer(u32),
    FloatingPoint(f32),
    String(String),
    Plus,
    Minus,
    Percent,
    Exclamation,
    ParenOpen,
    ParenClose,

    KeywordIntens,
    KeywordColor,
    KeywordPosition,
    KeywordStrobe,
    KeywordMaintenance,

    KeywordThru,
    KeywordFull,
    KeywordHalf,
    KeywordOut,
    KeywordHome,
    KeywordManSet,
    KeywordRecord,
    KeywordCreate,
    KeywordGroup,
    KeywordMacro,
    KeywordCommandSlice,
    KeywordSequence,
    KeywordFader,
    KeywordButton,
    KeywordFor,
    KeywordAs,
    KeywordTo,
    KeywordRename,
    KeywordClear,
    KeywordPreset,
    KeywordTest,
    KeywordFixturesSelected,

    Eof,
}

impl std::fmt::Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::Integer(n) => write!(f, "{}", n),
            Token::FloatingPoint(n) => write!(f, "{}", n),
            Token::String(s) => write!(f, "\"{}\"", s),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Percent => write!(f, "%"),
            Token::Exclamation => write!(f, "!"),
            Token::ParenOpen => write!(f, "("),
            Token::ParenClose => write!(f, ")"),
            Token::KeywordIntens => write!(f, "intes"),
            Token::KeywordThru => write!(f, "thru"),
            Token::KeywordFull => write!(f, "full"),
            Token::KeywordHalf => write!(f, "half"),
            Token::KeywordOut => write!(f, "out"),
            Token::KeywordHome => write!(f, "home"),
            Token::KeywordManSet => write!(f, "manset"),
            Token::KeywordRecord => write!(f, "record"),
            Token::KeywordGroup => write!(f, "group"),
            Token::KeywordMacro => write!(f, "macro"),
            Token::KeywordCommandSlice => write!(f, "commandslice"),
            Token::KeywordRename => write!(f, "rename"),
            Token::KeywordClear => write!(f, "clear"),
            Token::KeywordColor => write!(f, "color"),
            Token::KeywordPosition => write!(f, "position"),
            Token::KeywordStrobe => write!(f, "strobe"),
            Token::KeywordMaintenance => write!(f, "maintenance"),
            Token::KeywordPreset => write!(f, "preset"),
            Token::KeywordTest => write!(f, "test"),
            Token::KeywordFixturesSelected => write!(f, "~"),
            Token::KeywordCreate => write!(f, "create"),
            Token::KeywordSequence => write!(f, "sequence"),
            Token::KeywordFader => write!(f, "fader"),
            Token::KeywordButton => write!(f, "button"),
            Token::KeywordFor => write!(f, "for"),
            Token::KeywordAs => write!(f, "as"),
            Token::KeywordTo => write!(f, "to"),
            Token::Eof => write!(f, "Eof"),
        }
    }
}
