name: test-and-build

on:
  push:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always

jobs:
  lint_test_and_build:
    name: Lint and Test demex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: setup toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Install apt dependencies
        run: sudo apt-get update && sudo apt-get install build-essential pkg-config libasound2-dev libudev-dev libx11-dev libxkbcommon-dev libxkbcommon-x11-0 libxkbcommon-x11-dev

      - name: cargo test
        run: cargo test --all-features

      - name: rustfmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all --all-features --tests

      - name: Build and upload
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demex
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
